//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanhBaDienThoai.Models
{
    using Microsoft.Ajax.Utilities;
    using System;
    using System.Collections.Generic;

    public partial class ThongTinLienHe
    {
        public int ID { get; set; }
        public string HoTen { get; set; }
        public string BietDanh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
    }
}
